### ISSUE TITLE
Adding a screenshot ?

### ISSUE THREAD

**Issue by rgarrigue** [manbearwiz/youtube-dl-server#1]
Hi @manbearwiz 

Would you mind adding a screenshot of your server somewhere in the repo & linked in the REDME.md ? Just for a quick look :-)

Thanks,

**Comment by manbearwiz** [comment]
Done https://github.com/manbearwiz/youtube-dl-server/commit/6821ef2ab608d7ff4156d4b9ccca3e8fcbe63f96
