### ISSUE TITLE
chrome/opera extention

### ISSUE THREAD

**Issue by nwgat** [manbearwiz/youtube-dl-server#10]
would be cool if there was a extension companion to send current open tab url when you click icon in chrome/opera to youtube-dl-server

**Comment by manbearwiz** [comment]
how about a bookmarklet? something like this should work

```
javascript:!function(){fetch("http://127.0.0.1:8080/youtube-dl/q",{body:new URLSearchParams({url:window.location.href,format:"bestvideo"}),method:"POST"})}();
```

**Comment by fsjack** [comment]
It works!
