### ISSUE TITLE
Docker image is out of date

### ISSUE THREAD

**Issue by sorvis** [manbearwiz/youtube-dl-server#101]
Hello,

It looks like the existing python script in the repository does not match the latest version of the python script in dockerhub. Just wondering if that was on purpose or a miss? I noticed this because the / route is not redirecting correctly, but does redirect correctly when run the script locally.

**Comment by manbearwiz** [comment]
can you make sure you are using the master tag?

`docker pull kmb32123/youtube-dl-server:master`

**Comment by sorvis** [comment]
@manbearwiz thank you for the reply that does resolve the issue. Curious why the latest tag is there since most people will likely go for that first?

**Comment by manbearwiz** [comment]
Its setup so that the `master` tag is like the "beta" channel and `latest` is the latest tested release. I have just neglected to create a tested release in a few years.

**Comment by manbearwiz** [comment]
latest tag now points to a new 2.0 release https://hub.docker.com/r/kmb32123/youtube-dl-server/tags
