### ISSUE TITLE
V2 errors

### ISSUE THREAD

**Issue by MnM001** [manbearwiz/youtube-dl-server#102]
After updating the docker container to v2 I get this in the logs:

Updating youtube-dl to the newest version
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.2.1 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Requirement already satisfied: yt-dlp in /usr/local/lib/python3.10/site-packages (2022.7.18)
Requirement already satisfied: websockets in /usr/local/lib/python3.10/site-packages (from yt-dlp) (10.3)
Requirement already satisfied: brotli in /usr/local/lib/python3.10/site-packages (from yt-dlp) (1.0.9)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/site-packages (from yt-dlp) (2022.6.15)
Requirement already satisfied: mutagen in /usr/local/lib/python3.10/site-packages (from yt-dlp) (1.45.1)
Requirement already satisfied: pycryptodomex in /usr/local/lib/python3.10/site-packages (from yt-dlp) (3.15.0)

**Comment by manbearwiz** [comment]
Are there any issues? That is just a warning from the automatic system update at startup and can be ignored when running in a container.

**Comment by MnM001** [comment]
Yes - the container never starts.
That is the error it stops with.

**Comment by manbearwiz** [comment]
Fwiw I get those same warnings on startup but everything works as normal. I only see more log messages once I hit the server.

**Comment by MnM001** [comment]
Ok - I see now that the docker compose has changed and is not the same as previous versions.
Made the changes and all works OK now.
Thanks
