### ISSUE TITLE
Update function fails due to color in pip output

### ISSUE THREAD

**Issue by 0xE1** [manbearwiz/youtube-dl-server#109]
Update function fails due to color in pip output that is not expected since `print(output.decode("ascii"))` is used:
```
  File "/usr/src/app/./youtube-dl-server.py", line 141, in <module>
    update()
  File "/usr/src/app/./youtube-dl-server.py", line 75, in update
    print(output.decode("ascii"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 177: ordinal not in range(128)
```

I believe the argument --no-color should be added to prevent this issue

**Comment by manbearwiz** [comment]
should be fixed https://github.com/manbearwiz/youtube-dl-server/pull/105
