### ISSUE TITLE
Add an option to lock this site?

### ISSUE THREAD

**Issue by robocrax** [manbearwiz/youtube-dl-server#117]
Having this publicly facing means anyone can request as much content as they want and possibly fill up storage.

Is it possible to add authentication or an optional login section?

Or can this be handled by another web server?

Not sure if basicauth is enough but that should be enough to block a few attempts

**Comment by manbearwiz** [comment]
You can add basic authentication in your web server. Here is a tutorial for nginx but you should be able to find similar for any web server you prefer

https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
