### ISSUE TITLE
Ability to disable re-encode

### ISSUE THREAD

**Issue by PBXg33k** [manbearwiz/youtube-dl-server#12]
Would it be much work to make this tool more configurable? I would love to have the option to disable any form of re-encoding.

**Comment by manbearwiz** [comment]
The app will only re-encode if you chose one of the video options other than "Best Video". If you chose "Best Video" it will directly download the highest quality video and audio files available and then combine them. What format do you expect the non re-encoded file to be in?

**Comment by PBXg33k** [comment]
Ah, i'll test that option. Thanks.

I would expect the best version YouTube has to offer for the given URI

**Comment by manbearwiz** [comment]
yeah if you chose the "Best Video" option it will use this format specifier `bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]` to download and will not reencode. You can read more about what exactly this format means [here](https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection)
