### ISSUE TITLE
Docker Hub tag's

### ISSUE THREAD

**Issue by thesourcecodes** [manbearwiz/youtube-dl-server#136]
Docker tag latest is not beeing used i guess, Instead there is an tag called: master wich is pretty up to date. Can you update so latest is the latest build ? or is this "normal" behavior

**Comment by manbearwiz** [comment]
yep good call. that was missed in the change from dockerhub to github actions. fixed in https://github.com/manbearwiz/youtube-dl-server/commit/4f6627e516214e4f0b77c64e5d1c43e02363cb9d
