### ISSUE TITLE
Bundle the libraries in the image, so clients aren't constantly downloading them from CDNs

### ISSUE THREAD

**Issue by manad777** [manbearwiz/youtube-dl-server#19]
JQuery, Popper, and Bootstrap should be bundled. This is a self-hosted webapp after all.

**Comment by manbearwiz** [comment]
I don't think this would really get us anything. The 3 of them combined are <50 KB and should be cached for subsequent calls. If this app had any front-end js I would agree with you but I don't think its worth adding a build step for it.
