### ISSUE TITLE
Added videos not downloading automatically anymore

### ISSUE THREAD

**Issue by Fribb** [manbearwiz/youtube-dl-server#20]
I updated the docker image yesterday and was wondering why no new videos are being downloaded.

In my case, I add videos through flexget by the channels RSS feed and add them to the docker image through the curl command you provided (curl -X POST --data-urlencode "url={{url}}" http://{{address}}:8080/youtube-dl/q).

But since the update to the latest version yesterday they just sit there in the download queue and don't get resolved. The docker logs command shows the following for an example video.

> Added url https://www.youtube.com/watch?v=ds0cmAV-Yek to the download queue
> 192.168.170.7 - - [10/Dec/2018 21:22:14] "POST /youtube-dl/q HTTP/1.1" 200 100

and now it sits in the download queue /youtube-dl/q

> [\"https://www.youtube.com/watch?v=ds0cmAV-Yek\", {\"format\": null}]

maybe the format: null is the reason for this?

**Comment by manbearwiz** [comment]
I use this image in a similar manner and just confirmed it is still working for me. After doing the curl post the same way you mentioned, I receive 

```
{"success": true, "url": "https://www.youtube.com/watch?v=Y8ibdsPYOgw", "options": {"format": null}}`
```

and the server falls back to using the `bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]` format.

Want to try using the format param to see if you get different results? Something like

```
curl -X POST --data-urlencode "url=https://www.youtube.com/watch?v={{id}}" --data-urlencode "format=mp3" http://127.0.0.1:8080/youtube-dl/q
```

**Comment by Fribb** [comment]
hmm, seems like it works again after recreating the image.

tried it with both the format set in the curl and without and the video is downloaded with either solution again. Seems like my image just had a hiccup and needed to be renewed.
