### ISSUE TITLE
Prettier screen after submit

### ISSUE THREAD

**Issue by nemchik** [manbearwiz/youtube-dl-server#21]
Right now after submitting a url the page is a bit plain. Can this be made prettier? Maybe have a link to return to the initial page?

**Comment by nemchik** [comment]
Another idea for this would be to redirect back to the main page after 3-5 seconds if the message was successful, and not redirect at all if there was a failure but instead show a link or button to return to the main page. This way if all is well there's no need to sit on the status page, but if there's any kind of error the user would have to manually acknowledge it before being redirected.

**Comment by jesse-troy** [comment]
I much prefer @nemchik 's idea here. Any possibility of this happening?

**Comment by Wdavery** [comment]
Another vote for this in 2020!

**Comment by manbearwiz** [comment]
done https://github.com/manbearwiz/youtube-dl-server/commit/b9c20b5432e7fc1fc03fd678ed832e0a11d4044e
