### ISSUE TITLE
[Feature] Adds login / basic autentication

### ISSUE THREAD

**Issue by RicardoVelaC** [manbearwiz/youtube-dl-server#25]
Adds basic autentication for prevent use from others

**Comment by apinter** [comment]
Sounds like something that you can easily resolve with a reverse nginx proxy and htaccess ( [guide](https://community.openhab.org/t/using-nginx-reverse-proxy-authentication-and-https/14542) )

**Comment by RicardoVelaC** [comment]
Thanks!! I'll try it on a Synology, it's a little bit different but Synology uses nginx too

**Comment by manbearwiz** [comment]
Thanks @apinter ! I had been meaning to look into this as I thought that would be the correct way to go.

@RicardoVelaC did you get it working?

**Comment by RicardoVelaC** [comment]
@manbearwiz I don't try yet...
I use it on Synology docker version, and I've never needed to configure it this way.
The others docker images implement that via login page or HTTP basic access authentication.
I think this way it more easy and automated with docker ENV
