### ISSUE TITLE
Bookmarklet not work

### ISSUE THREAD

**Issue by ohnggni** [manbearwiz/youtube-dl-server#28]
Bookmarklet using javascript does not work. Could you please check if working well?

**Comment by manbearwiz** [comment]
Are you getting some kind of error? Can you verify you have modified the host in the bookmarklet code to point to the correct address and port for your youtube-dl-server isntance?

**Comment by ohnggni** [comment]
There was no error message. Of course, I modified the host and port and I am successfully using with them on the web-page. Only the bookmarklet does not work. My web-browser is Safari on macOS.

**Comment by ohnggni** [comment]
I've solved the problem by myself.
The URL must start not 'http' but 'https.'
In order to do that, I used 'reverse proxy' function of synology nas to match my domain starting 'https' with my original URL(aka. http://192.168.1.21:8888).

After that, the bookmarklet works like a chime!
