### ISSUE TITLE
youtube_dl.utils.DownloadError: ERROR: unable to download video data: <urlopen error _ssl

### ISSUE THREAD

**Issue by EggyCheng** [manbearwiz/youtube-dl-server#31]
Added url https://www.youtube.com/watch?v=3Z-V8cNX11Y to the download queue                                          
172.17.0.1 - - [20/Mar/2019 06:26:49] "POST /youtube-dl/q HTTP/1.1" 200 107                                          
[youtube] 3Z-V8cNX11Y: Downloading webpage                                                                           
[youtube] 3Z-V8cNX11Y: Downloading video info webpage                                                                
172.17.0.1 - - [20/Mar/2019 06:34:36] "GET /w00tw00t.at.ISC.SANS.DFind:) HTTP/1.1" 404 798                           
ERROR: unable to download video data: <urlopen error _ssl.c:1039: The handshake operation timed out>                 
 process_info                                                                                                        
    self.report_error('unable to download video data: %s' % error_to_compat_str(err))                                
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 622, in report_error                   
    self.trouble(error_message, tb)                                                                                  
  File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 592, in trouble                        
    raise DownloadError(message, exc_info)                                                                           
youtube_dl.utils.DownloadError: ERROR: unable to download video data: <urlopen error _ssl.c:1039: The handshake opera
tion timed out>         

－－－－－
how to fix it?

**Comment by fsjack** [comment]
openssl and ca-certificates is needed.
apk update && apk add ca-certificates && update-ca-certificates && apk add openssl

**Comment by manbearwiz** [comment]
I think this might have just been an outdated version of youtube-dl? I was able to download the video linked without errors.
