### ISSUE TITLE
Python 2 ChainMap and pathlib

### ISSUE THREAD

**Issue by jeffli678** [manbearwiz/youtube-dl-server#34]
In Python 2, there is no ChainMap inside the collections. So I would suggest changing the code from `from collections import ChainMap` to:

```
try:
    from collections import ChainMap
except ImportError:
     from chainmap import ChainMap
```

Meanwhile, add pathlib and ChainMap to requirements.txt.

**Comment by manbearwiz** [comment]
Sorry. Don't plan on supporting python 2
