### ISSUE TITLE
default output path (dir) is an absolute path

### ISSUE THREAD

**Issue by jeffli678** [manbearwiz/youtube-dl-server#35]
The default output template is `/youtube-dl/%(title)s [%(id)s].%(ext)s`, this is an absolute path and Python will most likely fail to create it. should it be `youtube-dl/%(title)s [%(id)s].%(ext)s`, which will be relative to the repo directory?

**Comment by manbearwiz** [comment]
I intend this to run in docker by default. In that case, the absolute path is correct, and the volume can be mounted to whatever directory the user wants through docker. If you are running via python, you can set a different output path with the `YDL_OUTPUT_TEMPLATE` environment variable.
