### ISSUE TITLE
Fix for breaking change (youtube-dl 2019.04.24)

### ISSUE THREAD

**Issue by TurboCheetah** [manbearwiz/youtube-dl-server#37]
All old youtube-dl deployments are currently broken and will fail with the following error
> "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Please fix thx

**Comment by manbearwiz** [comment]
Triggered a new build with 2019.4.24
