### ISSUE TITLE
Error 403 forbidden, unable to download video data

### ISSUE THREAD

**Issue by mhbates** [manbearwiz/youtube-dl-server#42]
Getting the following error. Does youtube-dl need to be updated in the image?

> WARNING: unable to extract channel id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> ERROR: unable to download video data: HTTP Error 403: Forbidden
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1909, in process_info
>     partial_success = dl(fname, new_info)
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1854, in dl
>     return fd.download(name, info)
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 364, in download
>     return self.real_download(filename, info_dict)
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
>     establish_connection()
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
>     ctx.data = self.ydl.urlopen(request)
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2227, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
>     return self._call_chain(*args)
>   File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 403: Forbidden
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.7/threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "./youtube-dl-server.py", line 60, in dl_worker
>     download(url, options)
>   File "./youtube-dl-server.py", line 106, in download
>     ydl.download([url])
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2008, in download
>     url, force_generic_extractor=self.params.get('force_generic_extractor', False))
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 807, in extract_info
>     return self.process_ie_result(ie_result, download, extra_info)
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 861, in process_ie_result
>     return self.process_video_result(ie_result, download=download)
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1642, in process_video_result
>     self.process_info(new_info)
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1917, in process_info
>     self.report_error('unable to download video data: %s' % error_to_compat_str(err))
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 624, in report_error
>     self.trouble(error_message, tb)
>   File "/usr/local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 594, in trouble
>     raise DownloadError(message, exc_info)
> youtube_dl.utils.DownloadError: ERROR: unable to download video data: HTTP Error 403: Forbidden
>

**Comment by manbearwiz** [comment]
Want to try pulling latest? I just push a new build.

**Comment by mhbates** [comment]
Fixed, thank you!
