### ISSUE TITLE
Request: Error handling on download thread

### ISSUE THREAD

**Issue by GeorgeHahn** [manbearwiz/youtube-dl-server#45]
Queue downloading does not recover after any error occurs on the download thread.

This is the same issue as: https://github.com/manbearwiz/youtube-dl-server/issues/43

**Comment by miguelarios** [comment]
I'm experiencing this same issue. Did you @GeorgeHahn find a solution?

**Comment by GeorgeHahn** [comment]
Nope. This issue could be fixed pretty easily with a PR, but the project appears to be unmaintained. I think I remember fixing this locally, but my server was stolen and I never pushed the code to my fork.

I haven't tried it, but my notes mention https://github.com/Tzahi12345/YoutubeDL-Material as a promising alternative.

**Comment by manbearwiz** [comment]
Yeah somehow I stopped getting notified about issues in this repo. I had no idea this many people were using it. I pushed an update to switch from bottle to starlette and got rid of the queue and download worker in favor of a starlette `BackgroundTask`. I think this should address the issue.
