### ISSUE TITLE
Not downloading the best fps using "Best Video"

### ISSUE THREAD

**Issue by JoeSzymkowicz** [manbearwiz/youtube-dl-server#56]
Tried downloading a video with 50fps 1080p using the "Best Video" option, and outputted file was 1080p, but only 25fps. Am I doing something wrong?

Example: https://www.youtube.com/watch?v=h2Tzd7MiOj8

**Comment by JoeSzymkowicz** [comment]
"Best" is subjective i guess in the the base youtube-dl package.

**Comment by manbearwiz** [comment]
If you want to try downloading it with the youtube-dl cli and find the correct arguments to get it working I can try to incorporate it into this. The documentation for the cli is here https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection
