### ISSUE TITLE
strange connection in docker?

### ISSUE THREAD

**Issue by PikuZheng** [manbearwiz/youtube-dl-server#57]
```
# netstat -alnp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        4      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1/python
tcp        0      0 172.18.0.2:8080         193.106.31.98:22        ESTABLISHED 1/python
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
```
after the strange established connection, bottle stop to acception other requests.
any idea?

**Comment by PikuZheng** [comment]
Ok. The problem is a connect established to YTDL and droped by firewall. After that, YTDL web hang and not response to other connections.

**Comment by manbearwiz** [comment]
I fixed the issue with the download thread crashing. If you are still using this, checkout the latest version.

**Comment by PikuZheng** [comment]
Oh I see. A big update.
I tried use threading.Thread for keep bottle running. It works fine. fyi.
