### ISSUE TITLE
output folder

### ISSUE THREAD

**Issue by JokerShades** [manbearwiz/youtube-dl-server#61]
Hi, is there a way to specify the output folder?

**Comment by nbr23** [comment]
Hello,
Yes, you can modify line 20 in youtube-dl-server.py to update the YDL_OUTPUT_TEMPLATE to point to the directory of your choice (by default, it goes to /youtube-dl/)

**Comment by manbearwiz** [comment]
You can also set this through an environment variable so you don't have to modify code. Something like this if you are running via python.

```shell
YDL_OUTPUT_TEMPLATE="/home/user/%(title)s [%(id)s].%(ext)s" python3 -u ./youtube-dl-server.py
```
