### ISSUE TITLE
Query: How to use --no-mtime

### ISSUE THREAD

**Issue by darksky82** [manbearwiz/youtube-dl-server#66]
When I run docker run with "--no-mtime" it errors out. How/where exactly do I use this parameter ?

**Comment by darksky82** [comment]
Any help?

**Comment by manbearwiz** [comment]
Not sure if you are still using this, but I got around to adding an option to disable that. Setting the environment variable `YDL_UPDATE_TIME` to `False`, or anything other than `True` really, will use the downloaded time as the modified date.
