### ISSUE TITLE
Remove /youtube-dl from domain

### ISSUE THREAD

**Issue by JacobOkanta** [manbearwiz/youtube-dl-server#67]
I am running the server using docker-compose, and using a subdomain through an Nginx reverse proxy. Would it be possible to remove the /youtube-dl that is required to be added to the subdomain to access the service or redirect from the base domain to /youtube-dl?

**Comment by manbearwiz** [comment]
added a redirect from root https://github.com/manbearwiz/youtube-dl-server/commit/b9c20b5432e7fc1fc03fd678ed832e0a11d4044e
