### ISSUE TITLE
youtube_dl.utils.DownloadError: [0;31mERROR:[0m unable to open for writing: [Errno 36] Filename too long:

### ISSUE THREAD

**Issue by mick-pihole** [manbearwiz/youtube-dl-server#68]
hope there is a fix. please cut the filename string to fit the system limit.

**Comment by AkgunFatih** [comment]
this is a youtube-dl issue
you can find a workaround here https://github.com/ytdl-org/youtube-dl/issues

**Comment by manbearwiz** [comment]
@mick-pihole  I added formatting to truncate the title to 200 characters and avoid hitting this limit. Let me know if you still run into it after getting latest.
