### ISSUE TITLE
Download video-clips in a playlist at once

### ISSUE THREAD

**Issue by ohnggni** [manbearwiz/youtube-dl-server#7]
Thank you for your great contribution, first.
I'd like to download video-clips in a playlist of youtube at once.
Could you please implement this function?

**Comment by ohnggni** [comment]
At this moment, I can download all clips in a playlist. Therefore I close this issue.

**Comment by coolguymatt** [comment]
How did you do this? When I enter the playlist URL it just downloads the first video.

**Comment by ohnggni** [comment]
> How did you do this? When I enter the playlist URL it just downloads the first video.

Which URL do you try to download? I didn't do any special action.
