### ISSUE TITLE
USE Bookmarklet Error

### ISSUE THREAD

**Issue by ladudu** [manbearwiz/youtube-dl-server#81]
Use the Bookmarklet :
`javascript:!function(){
fetch("http://192.168.1.105:8080/youtube-dl/q",{body:new URLSearchParams({url:window.location.href,format:"mp3"}),method:"POST"})
}();`
got error with the content must be served over HTTPS.
VM547:1 Mixed Content: The page at 'https://www.youtube.com/watch?v=rVEMTxg_LrU' was loaded over HTTPS, but requested an insecure resource 'http://192.168.1.105:8080/youtube-dl/q'. This request has been blocked; the content must be served over HTTPS.

**Comment by manbearwiz** [comment]
You could use a reverse proxy in front of youtube-dl to accept https requests
