### ISSUE TITLE
yt-dlp Support

### ISSUE THREAD

**Issue by N7KnightOne** [manbearwiz/youtube-dl-server#89]
Are there any plans to swap the backend to yt-dlp?

**Comment by dginovker** [comment]
Looks like you could swap it out in the requirements.txt: https://pypi.org/project/yt-dlp/

**Comment by manbearwiz** [comment]
done https://github.com/manbearwiz/youtube-dl-server/commit/9eed713ebe20d07b90b07e8a084813142e43878a
